### ISSUE TITLE
When i search in a certain IRC Chat, it crashed (Huge Logging of it)

### ISSUE THREAD

**Issue by Zerowalker** [hexchat/hexchat#1280]
As topic says.

My guess it's because i have huge logs of it, so it needs to search that, so perhaps a memory leak or something?

**Comment by SquareWheel** [comment]
Can confirm.  When I hit Ctrl+F and any key, Hexchat immediately crashes, every time.  I have doubled my buffer size however so perhaps related.

**Comment by TingPing** [comment]
I have experienced this just a few times but I can never reproduce it to get a traceback...What is your scrollback size set to?

**Comment by SquareWheel** [comment]
Currently set to 1,000 lines.

**Comment by Zerowalker** [comment]
Mine is 4k.

**Comment by SquareWheel** [comment]
Possibly a memory leak as it seems more crashy when it's been running a while.  I thought it was every time, but I found it lets me do a search immediately after restarting the program.

Also note I have regex deselected.  That does seem to increase likelihood of crashing.

Will gather more data.  Is there a crashlog or anything I can upload?

**Comment by TingPing** [comment]
>Will gather more data. Is there a crashlog or anything I can upload?

Only if you know how to use a debugger.

I don't think any leak is related, I think xtext is just garbage and does something stupid like usual.

**Comment by RichardHitt** [comment]
SquareWheel thanks for helping investigate this problem.  The search code is my code, and it's been very successful, well-designed, nicely-commented, plays well with others ('others' being the many features of the hexchat text buffer and window), if I do say so myself.  Do you run a linux distro?  If you cannot easily reproduce the crash, I recommend this stress test:  In the Find: window, check the "Regex" box, and then merely type a single period in the search textbox.  This will select, as an individual selected item, each and every visible character in your entire text buffer.  As to the buffer's size,  I run comfortably with a "Scrollback lines:" setting of 50000, fifty thousand, and I've had no crashes at all.

With linux, and bash, first allow coredump files by giving the command "ulimit -c unlimited" and then start hexchat and try to reproduce the problem.  If you can build your own hexchat, that would be helpful, as it would include symbol information that is missing from the stripped distributed version; or I could make such a hexchat for you.

If you successfully get a coredump, I'd need to look at both it and the executable binary of hexchat you were running that produced it.  I would be very grateful if you managed to do this!

Questions, problems, clarifications?

**Comment by SquareWheel** [comment]
Hey Richard,

Thanks for your help.  I am running Windows unfortunately, but am familiar with regex.  If you are able to compile a Windows version with more debugging flags I would be happy to run it.  I use the portable version of Hexchat if that's relevant.

I took a quick video to get a demonstration of the crash.
https://www.youtube.com/watch?v=p86_N7NWSTo

Looks like OBS kept some black bars though - sorry about that.
Note that regex is disabled, and it's only when I type a key to search that it crashes.

I'm not a C programmer so I'm not familiar with the tools, debuggers and such.  I can follow directions if necessary though.

Let me know what I can do.

**Comment by Arnavion** [comment]
Have you tried a test build yet? An xtext crash was fixed there that isn't part of a release yet.

**Comment by SquareWheel** [comment]
Nope, I'm using the latest stable.  Will check the test builds out.  Thanks.

**Comment by SquareWheel** [comment]
I've been running the latest unstable build for about 20 hours and have experienced no crashes yet.  I've done a fair amount of testing in an attempt to crash it.  It's tough to say with 100% certainty, but this seems to have resolved the issue for me.

Thanks again for the suggestion.

**Comment by TingPing** [comment]
I am pretty sure I have experienced the crash in git builds. I can't for certain say though since I could never reliably repro...

**Comment by RichardHitt** [comment]
WesCook If you are running a Linux distro, here's what you can do when hexchat crashes:  Use the command "coredumpctl gdb".  Then, when the gdb command prompt appears, use the command "where".  It will print out a stack traceback.  If you could furnish the lines of that stack traceback, it would be very helpful.

**Comment by WesCook** [comment]
Hi Richard,

I am unfortunately running Windows 8.1, not a Linux distro.  If there's any other debug tools I can run, I'd be happy to try.

The latest unstable build at the time seemed to reduce crashes, but I quickly learned they did still occur.  I've not updated my build in about 2 months now though, so could try again.

**Comment by Arnavion** [comment]
Create the reg key as described in http://stackoverflow.com/a/20238046/545475 (change dump directory as appropriate), get HC to crash, upload the dump somewhere private (it will contain all private info like channel history, network passwords, etc.) and send us the URL somehow, along with which specific test build version you used.

If you can get it to crash with an empty config that's even better, but if scrollback size is involved that may not be possible.

If you don't want to share the dump and know how to use windbg the usual way, then do that and get the faulting stack trace.

**Comment by WesCook** [comment]
I'm running the portable version - would the registry key still be used?

As I use IRC for private conversation, I also do not think I'd be able to upload that data.  Not unless I'm able to filter it first, though I'm guessing it'll be in a binary form.

I'll look into windbg.

**Comment by Arnavion** [comment]
Change DumpType to 0 and leave CustomDumpFlags as 0, then it'll only contain the stack trace for all threads, no private info.

**Comment by WesCook** [comment]
I've done so, and captured a much smaller dump.

Download: https://cloudup.com/c3d_TkQUblo

Let me know if that helps.

**Comment by Arnavion** [comment]
You didn't say which test build you used.

**Comment by WesCook** [comment]
That was a build from 2 months ago.  Unsure of build number, but main version is 2.11.0.  I'll grab the latest Windows unstable, which I believe is available here:

    https://dl.hexchat.net/hexchat/testing/HexChat-2.11.0-x64-f7bea16.exe

Will report back with crash log, assuming the issue still remains.

**Comment by TingPing** [comment]
Can any of you test a new build (https://dl.hexchat.net/hexchat/testing/) this may have been fixed by https://github.com/hexchat/hexchat/commit/c8539b93fe65977ee507b473e9dd62a1cc7bec53.

**Comment by hub2git** [comment]
Crashes for me,too. Using Linux Mint cinnamon 18.1. hexchat is from official (I.e, Mint) repository. Updated to whatever the latest version in the repository is. Please let me know how to give you the info you need to figure out the problem

@TingPing
Has not the c8539b9 commit you refer to been merged into Mint repo? I would think that one entire year would be plenty of time for the fix to make its way into Mint 18.1.

**Comment by TingPing** [comment]
@hub2git That isn't how Mint (Ubuntu LTS) works, you get one major update every 2 years so the next update you get is in 2018 and their current version is from 2014.

You can use the PPA on https://hexchat.github.io

**Comment by hub2git** [comment]
@TingPing, thank you for clarifying for me that LTS is not updated often. I I was on LTS. :)
I went to https://hexchat.github.io/downloads.html, then I went to "[OverCoder’s PPA](https://launchpad.net/~overcoder/+archive/ubuntu/hexchat) (Latest stable)" and added the PPA. I've ran Update Manager and installed 2.12.4+ds1-0ubuntu2~ppa1 (uploaded 2016-12-25). I'll try the new Hexchat and see if it crashes when I do Control-F search.

**Comment by TingPing** [comment]
I have actually encountered it recently so I don't believe it is solved.

**Comment by hub2git** [comment]
@TingPing   ah, thanks for confirming bug is still alive. I guess we should just wait till it's solved? What will it take to get the bug quashed? Would it help if I provide a log, or is that unnecessary?

**Comment by TingPing** [comment]
There are no logs, somebody familiar with debugging C just needs to reproduce and look into it. It rarely happens to be so I have a hard time reproducing it.

**Comment by hub2git** [comment]
OK, so since I know nothing about C, I can't help out? Are you saying that the only person who can look into the problem is someone who knows C?

**Comment by mB-PiBox** [comment]
> OK, so since I know nothing about C, I can't help out? Are you saying that the only person who can look into the problem is someone who knows C?

@hub2git would assume that's kinda what he is saying, since it would take someone that knows the language (or similar language) to figure out whats causing the issue. He's also saying its hard to know whats 'causing the issue, if you don't experience the issue in order to debug it. Some issues you can just look at see that something is off/wrong with the program code, but that doesn't fall true for most bugs/issues. Anyways, since he doesn't have the issue (or at least it might happen 0.5% of the time) its hard to resolve it since he can't forcibly make the error occur (ie reproduce it)

**Comment by hub2git** [comment]
thanks for your reply, @mB-PiBox. I don't know any programming, but if I
reproduce the crash, I thought I could submit some logs. Guess not. I'll
just patiently wait for a fix, or try some other chat program for now.

**Comment by bexelg** [comment]
Every time I hit Ctrl-F and then a key, Hexchat crashes.

http://termbin.com/wlrq
http://termbin.com/tlnq
