### ISSUE TITLE
[Request] Delay command...  AGAIN...

### ISSUE THREAD

**Issue by VasVadum** [hexchat/hexchat#1524]
Ok, so clearly you guys misunderstood me in #1516 when I asked for a delay command.  You told me timer which delays one command, not the entire line following the command which really screwed things up.  Thank you for that.  I want an actual delay I can add to my list, where I add a delay before commands following it are run.  So I have to post again because you gave me this "timer" thing.

C=nickserv identify PasswordHere
C=ghost VasVadum PasswordHere
C=ghost Vas PasswordHere
C=delay 2
C=nick VasVadum
C=delay 2
C=nick Vas
C=ECHO #steam #TechFurs #Nupe #Nupe #Nupe #floofdragons
C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html
C=mode Vas_Vadum +px
C=mode VasVadum +px
C=mode Vas +px
C=delay 2
C=join #Nupe,#Nupe,#Nupe
J= +13 more
J=#Starcraft
J= +5 more

Also, your timer version would fail, because you can't timer the "J=" section unless I stop using that feature of HexChat, and instead edit my commands every single time to change /join 1,2,3,4,5,6,7 every time I wanna add a new one in there.

**Comment by Arnavion** [comment]
>Ok, so clearly you guys misunderstood me in #1516 when I asked for a delay command.

1. The person who answered you in #1516 was not a dev, so I'll appreciate it if you drop the accusatory tone of "you guys" telling you things. Regardless...

1. The answer you were given was actually correct, but you misunderstood and misused it.

You were again told more explicitly in #1521 how to do it:

>If you want a complicated set of order-dependent commands then either use progressively larger timers or write a script.

Note how the answer in #1516 is also telling you the same thing - to use progressively larger timers so as to impose an ordering on depedent commands.

>Also, your timer version would fail, because you can't timer the "J=" section unless I stop using that feature of HexChat, and instead edit my commands every single time to change /join 1,2,3,4,5,6,7 every time I wanna add a new one in there.

Yes, you cannot apply a timer to an autojoin channel. If you absolutely need to use a timer then use it with a join command, or with a script.

Exactly *why* you have a list of commands to change nicks multiple times on connect and only then join is only known to you.

**Comment by VasVadum** [comment]
"We don't want to add a new feature, you should just do it yourself." got it.

**Comment by Arnavion** [comment]
"We don't want to add a new feature that appears to have insufficient justification to be part of the main product. Especially so since it's almost certain that the whole basis for having that feature is invalid. You should just do it yourself since you're the only one who seems to need it."

**Comment by VasVadum** [comment]
Also, the reason I have them is so that no one can take my official names.  I use a short name during IRC normal usage, but if I don't touch a name in my group for a while, it de-registers even if I'm logged in on one of the group names.  Therefor, I have to /nick each one.

Now that I've taken out the timer, mode always fails, not seeing any of the names as existing.

Progressively large timers ignore the join, therefor we are required to use a script or a join command system, making the client useless because you have to write your own script to do it or use timer commands and annoy people in other channels when you have to change your nick twice after auto join activated.

**Comment by Arnavion** [comment]
>Now that I've taken out the timer, mode always fails, not seeing any of the names as existing.

Again, from #1521 

>In any case even if you removed the use of timer, the commands would still be sent in close succession, so it's possible the server will drop them.

>Progressively large timers ignore the join, therefor we are required to use a script or a join command system...

Correct, as you've already said multiple times and I've acknowledged each time.

>...and annoy people in other channels when you have to change your nick twice after auto join activated.

People don't get annoyed by that.

Besides, I doubt your network expires nicks so rapidly that you have to grab them every connect, so really the whole problem is of your own making.

**Comment by VasVadum** [comment]
Actually I was banned from a channel for it.  And yes, one of my names seemed to have expired after two weeks.  Currently, I have to reconnect every day, but eventually I won't have to reconnect every single day.

**Comment by VasVadum** [comment]
Seriously, it can't actually be that hard to add in a delay.  What's wrong with adding a delay for users in case they need it?  I'm no expert on coding.  In fact, I barely have a basic knowledge of javascript, I can't seem to get anywhere with programming.  However.  This is what I am seeing;

C=DELAY 5
If "delay", set var sleeptimer to x (whatever number was said)
sleep sleeptimer (5 seconds)

The client sleeps for that time, not running any further commands or auto joins for that duration of time.  Again, I'm no programming expert so I don't know how it would ACTUALLY look, or work.  I just don't think it is -that- hard to do.  Hard for someone without programming skills of any kind, yes.  But I for some reason feel anyone with a moderate level of programming (less skill than it took making the client) could do it.

I'm sorry for being annoyed and passive aggressive, I've just been suffering these issues for a long time now.  Mostly the crashing issue has been the one to really annoy me but now I see that's been a 3 year long issue now and won't be fixed.  So I'm hoping to at least get the other two issues fixed, and was hoping you guys would add a delay, because I don't know scripting and can't "do it yourself" like you want me to.

**Comment by TingPing** [comment]
I closed it because functionally /timer can do exactly what you want, I believe at this point that has been explained. Adding a command that behaves how you explain would actually be significantly more work since some sort of command queue would need to be created completely changing how commands are ran in the client.

**Comment by VasVadum** [comment]
But timer can't stop the client's auto join feature, all those J= channels.
You're effectively telling me to abandon one of the features I use HexChat for and from now on manually use /join 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 now.  And edit this command every time I want to start auto joining another channel.  :/

**Comment by TingPing** [comment]
> But timer can't stop the client's auto join feature, all those J= channels.

Indeed, there is *Prefs > Advanced > Auto-join delay* though. The feature only exists to work around terrible authentication systems.

**Comment by VasVadum** [comment]
Well, I'll lookinto this and try to optimize my command list now that I know /umode exists.  I was only having problems because the client seems to do weird things with my command list.

**Comment by berrythesoftwarecodeprogrammar** [comment]
lol

**Comment by wowaname** [comment]
(This just caught my eye; I know the issue is closed.)
>So, what exactly is the point of HexChat if we have to write our own scripts anyway?
irssi users seem not to have a problem with writing their own scripts to extend functionality to how they want. I don't think that it is justified to ask the HexChat devs to spoonfeed someone requesting a feature that the majority simply does not need.

**Comment by VasVadum** [comment]
Well I noticed it isn't a problem of the command being run too fast.  It's a problem of HexChat not knowing how to do /umode +p or /mode Nick +p on startup.  It does it just fine on /reconnect, but it can't do it on startup.  It replaces nick, with servername so instead of running 
/mode Vas +p
It runs 
/mode furnet Vas +p
So yea.

**Comment by TingPing** [comment]
> Yeah, I tried setting up an auto-connect command "mode zahlia +p" and it just whines about Furnet not being a channel.

The cause of this was sort of documented here: https://github.com/hexchat/hexchat/commit/e7003ef9c6ef2e6615c96ce6bf2a19745f293793

To summarize HexChat is only sure if a nick is your nick after the server response with NICK. So you are playing with some very terrible timing specific stuff giving no regard for timing and obviously things won't line up.

**Comment by VasVadum** [comment]
If it was bad timing, then it would clearly work later, it doesn't.  It has to be run manually.  I had 20 /modes after the very last command was run.  Not a single one worked.  There appears to be 2 seconds between each command being run.

I also had timer 10, 20, and a 30 there.

I previously used multiple timers, 1, 2, 3, 4, 5, 7, 10, 15, and 30.
All timers used the same thing that was at the very time the timer was supposed to run, so if I used /umode while my name was still "Vas_Vadum", with a 30 second timer before it, then 30 seconds later, even after I changed my nick to Vas, it would run like /mode furnet Vas_Vadum +p

Timers are useless in this particular area, at least it seems.  Because in 3 of my tests, they run the command they were going to run at the time of activation even if it is wrong.  Which is the point of delay, which doesn't run another command until that delay has passed, while timer appears to gather the data it needed to run at that time and runs it x seconds later.

It is funny how everyone claims my timing is the problem, while all the other commands run perfectly fine in proper order, the only issue is /mode and /umode.  That is the only one I've ever had issues with.

**Comment by TingPing** [comment]
> after I changed my nick to Vas, it would run like /mode furnet Vas_Vadum +p

You are running mode on another nick...

Regarding including the server name that was fixed in the commit I linked above.

**Comment by VasVadum** [comment]
Hexchat 2.10.2 x64
»» FurNet :No such nick/channel

Still having the issue then.

> C=nickserv identify PasswordHere
> C=ghost VasVadum PasswordHere
> C=ghost Vas PasswordHere
> C=nick VasVadum
> C=nick Vas
> C=ECHO #steam #TechFurs #--- #poke-furry #--- #floofdragons #---
> C=join #---,#---,#---
> C=mode Vas +px (This was run 30 seconds after Nick)

Yes, timer doesn't work as I said..  I said if I put timer in, as the first command for example, specify 60 seconds.  These other commands all take 30 seconds tops to run.  30 more seconds after that, it uses the nick that was assigned at the time the timer first hit.  so it stays with "Vas_Vadum" instead of the nick that it is 60 seconds later.  That's what I'm saying.

And I just reinstalled HexChat today after downloading the latest version available so that I could get GTK themes working finally.  Silly that you have to reinstall to undo that one simple checkbox..  So I have the latest version available, is that fix included in the latest version?  I've seen people on a version higher than mine before, is there a custom location some beta version is at?

**Comment by wowaname** [comment]
How come I have never had an issue with setting umodes on connect with
HexChat?

**Comment by VasVadum** [comment]
How come another person told me they have the same issue? Perhaps it is not an issue with every machine?  Which would be weird.  I don't understand how one person would have an issue and one wouldn't because this issue has nothing to do with hardware config.  What is your command list then?

**Comment by wowaname** [comment]
>What is your command list then?

I no longer use HexChat.

**Comment by VasVadum** [comment]
....  Then why are you here commenting as if you know exactly what's going on...  If you don't use the application, you can't know these two bugs I've been encountering since the day I got it.  (This /mode issue, and the crash on auto reconnect too many times issue that has apparently been an issue since the application's inception.)

**Comment by wowaname** [comment]
I believe I am still fit to comment on the issue and still not have an answer to the question "What is your command list?".

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think your problem is that you're a furry

**Comment by wowaname** [comment]
On 15 11 05 05 51, Berry The Software Code Programmar wrote:
> i think your problem is that you're a furry

lmfao if anyone deletes this comment they're a tyrant
