### ISSUE TITLE
Linux Hexchat 2.14.0 default plugins fail to load

### ISSUE THREAD

**Issue by undeadrevo** [hexchat/hexchat#2141]
Upon starting Hexchat after updating via the package manager I am greeted with the following errors

> [18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/checksum.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?
[18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/sysinfo.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?
[18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/python.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?
[18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/lua.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?
[18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/fishlim.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?
[18:17:40]  AutoLoad failed for: /usr/lib/hexchat/plugins/perl.so
[18:17:40]  No hexchat_plugin_init symbol; is this really a HexChat plugin?

Looking at the compiled .so libs, they are all exactly 6.9kb in size.
Tried to use meson and ninja to compile it myself and it gave me the same thing.

**Comment by TingPing** [comment]
What distro?

**Comment by undeadrevo** [comment]
Arch Linux

**Comment by TingPing** [comment]
This was probably fixed by https://github.com/hexchat/hexchat/commit/d72249d91f97e609e755e57f50db30d7a3fc8a06

**Comment by TingPing** [comment]
I've linked this to the Arch maintainer.

**Comment by thyeun** [comment]
after a new update today from arch linux

but it is still missing on more plugin.

as you can see from the pic below.

![screenshot_2018-03-15_19-29-16](https://user-images.githubusercontent.com/1939446/37460848-771c830e-2887-11e8-8d42-e88de7db2c52.png)

**Comment by TingPing** [comment]
@thyeun Unrelated message, Arch does that on purpose read the optional dependencies of the package.

**Comment by thyeun** [comment]
@TingPing than the others two perl and python also can consider optional too, but why they still done that for python and perl and forget about lua?

meaning that Arch keep on forget about lua and only done for python and perl?

**Comment by TingPing** [comment]
@thyeun Arch marks them all as optional: https://www.archlinux.org/packages/community/x86_64/hexchat/

**Comment by thyeun** [comment]
@TingPing, yup, meaning that in future this will be the same issue, once hexchat upgrade to the new version. (i mean missing plugins of ```python, perl and lua```). 

I been trying from previous few version, once i upgrade to the next version (an example v 2.10 to 2.11) same missing plugin appear again.

so, if this is unrelated message, than i will consider it is normal. (because my team are asking me why same issue appear).

and thanks for pointed it out!!!

**Comment by TingPing** [comment]
The *plugin* isn't missing, the Arch package just allows you to not install their dependencies. It is a bad Arch policy IMO but not a bug.
