### ISSUE TITLE
Extra apple logo is created

### ISSUE THREAD

**Issue by zoeysiadevelopment** [hexchat/hexchat#994]
I had orignally mentioned this bug before, however it's quite annoying. There are two OSX menu buttons. the left one works as intended, the right one does nothing. screenshot is included.

screenshot![image](https://cloud.githubusercontent.com/assets/1834617/3087048/5e0bcc18-e54b-11e3-8553-56495aca9473.png)

**Comment by kenzierocks** [comment]
That bug is now closed as WONTFIX, it seems this should be resolved in HexChat?

**Comment by trollworkout** [comment]
is deff not fixed i give you that not in the latest release

**Comment by vioan** [comment]
still not fixed. And there is one more issue with the space between entries in the Hexchat Menu, see the screenshot here:
[HexChat.jpg](https://dl.dropboxusercontent.com/u/986121/HexChat.jpg)
